global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'nfe-drop-worker'
    static_configs:
      - targets:
          - 'localhost:9101'

  - job_name: 'nfe-drop-watcher'
    static_configs:
      - targets:
          - 'localhost:9100'
